version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    container_name: postgresDB
    volumes:
      - postgres_data:/home/Tadjer/var/lib/postgres/data
    expose:
      - 5432
    networks:
      - dev
    env_file:
      - ./private/.env.db

  backend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: "backend"
    networks:
      - dev
    env_file:
      - ./private/.env.backend
    ports:
      - 8000:8000
    volumes:
      - files_volume:/home/app/web/api/files
    depends_on:
      - db

volumes:
  postgres_data:
  files_volume:

networks:
  dev: